name: Test

on:
    pull_request:
        branches:
            - development
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - run: echo "Hello world"
